{{- if .Values.jaeger.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-jaeger-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    {{- toYaml .Values.jaeger.persistence.accessModes |nindent 4 }}
  storageClassName: {{ .Values.jaeger.persistence.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.jaeger.persistence.size }}
{{- end }}