{{- range .Values.configurations }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name | replace ".yaml" "" }}-jmx-exporter
  labels:
    app: {{ $.Chart.Name }}
    config: {{ .name | replace ".yaml" "" }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $.Chart.Name }}
      config: {{ .name | replace ".yaml" "" }}
  template:
    metadata:
      labels:
        app: {{ $.Chart.Name }}
        config: {{ .name | replace ".yaml" "" }}
    spec:
      containers:
      - name: jmx-exporter
        image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
        imagePullPolicy: {{ $.Values.image.pullPolicy }}
        ports:
        - name: metrics
          containerPort: {{ .port }}
        resources:
{{ toYaml $.Values.resources | indent 10 }}
        volumeMounts:
        - name: config-volume
          mountPath: /opt/jmx-exporter/config/{{ .name }}
          subPath: {{ .name }}
        args:
        - "{{ .port }}"
        - "/opt/jmx-exporter/config/{{ .name }}"
      volumes:
      - name: config-volume
        configMap:
          name: {{ $.Release.Name }}-jmx-exporter-config
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml $.Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml $.Values.affinity | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml $.Values.tolerations | nindent 8 }}
      {{- end }}
---
{{- end }}